# config.yaml

######################### input files and reference files ###############################################
FASTQ: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/fastq
samples: ["CreAHA_Glucose", "CreAHA_Carbon_Free", "CreAHA_Proline"]
Input: "Untag_control_for_HA"
repeats: ["Repeat1", "Repeat2"]
fqsuffix: fastq
gff: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/genome_info/FungiDB-65_AnidulansFGSCA4.gff
fasta: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/genome_info/FungiDB-65_AnidulansFGSCA4_Genome.fasta
gfolder: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/genome_info
gaf: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/reference/FungiDB-65_AnidulansFGSCA4_Curated_GO.gaf
obo: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/reference/go-basic.obo
KEGG_relation: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/reference/ani_KEGG_info.csv
output: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/output
############################ mapping parameters  #####################################################
ncores : 4
HT2index: /home/ruiwenchen/CreA_test_ChIPseq_pipeline_V2/genome_info/Anidulans_hisat2_index
trim5: 8
############################## call peaks parameters  #################################################
genomesize: 3e7
extsize: 200
bedGraphToBigWig: /home/ruiwenchen/Biosofts/bedGraphToBigWig
bedSort: /home/ruiwenchen/Biosofts/bedSort
############################## selectpeak parameters  #################################################
m: 2 #chipr select peaks which appear in at least m repeats.
h_t: 40 #high quality peak threshold, Peaks with summit bdg values greater than "h_t" will be classified as high quality.
############################### peak annotation parameters #############################################
type1_method: ATG
distance1: 2000
distance2: 1000
