# config.yaml
FASTQ: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/fastq
samples: ["AN7820_HA_1perglu_1perxyl"]
input: "WT_1perxyl_HA"
fqext: [1,2]
rep1: "R1"
rep2: "R2"
fqsuffix: fastq
gff: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/genome_info/FungiDB-65_AnidulansFGSCA4.gff
fasta: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/genome_info/FungiDB-65_AnidulansFGSCA4_Genome.fasta
gfolder: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/genome_info
output: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/output
ncores : 4
HT2index: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/genome_info/Anidulans_hisat2_index
genomesize: 3e7
extsize: 200
bedGraphToBigWig: /home/ruiwenchen/TF_ChIPseq_pipeline_test/bedGraphToBigWig
bedSort: /home/ruiwenchen/TF_ChIPseq_pipeline_test/bedSort
m: 2
h_t: 40 #high quality peak threshold, Peaks with summit bdg values greater than "h_t" will be classified as high quality.
type1_method: CDS
distance: 2000
gaf: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/reference/FungiDB-65_AnidulansFGSCA4_Curated_GO.gaf
obo: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/reference/go-basic.obo
KEGG_relation: /home/ruiwenchen/TF_ChIPseq_pipeline_test2/reference/ani_KEGG_info.csv